# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

#users
demo_user = User.create( email: 'demo@user.io', password: 'password', first_name: 'Demo', last_name: 'User', city: 'Bayside', state: 'NY', image_url: "https://avatars.githubusercontent.com/u/105556961?v=4")
demo_presenter = User.create( email: 'HireMe@YourCompany.pls', password: 'password', first_name: 'Tommy', last_name: 'Kim', city: 'New York', state: 'NY', image_url: "https://images.pexels.com/photos/14661/pexels-photo-14661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user3 = User.create( email: 'jenny@user.io', password: 'password', first_name: 'Jenny', last_name: 'Brown', city: 'Austin', state: 'TX', image_url: "https://images.pexels.com/photos/61100/pexels-photo-61100.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user4 = User.create( email: 'grace@user.io', password: 'password', first_name: 'Grace', last_name: 'Miller', city: 'Los Angeles', state: 'CA', image_url: "https://images.pexels.com/photos/53000/girl-beautiful-young-face-53000.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user5 = User.create( email: 'wilson@user.io', password: 'password', first_name: 'Wilson', last_name: 'Smith', city: 'Chicago', state: 'IL', image_url: "https://images.pexels.com/photos/25733/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user6 = User.create( email: 'will@user.io', password: 'password', first_name: 'Will', last_name: 'Smith', city: 'Houston', state: 'TX', image_url: "https://images.pexels.com/photos/23876/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user7 = User.create( email: 'jackyln@user.io', password: 'password', first_name: 'Jacklyn', last_name: 'Garcia', city: 'Phoenix', state: 'AZ', image_url: "https://images.pexels.com/photos/69494/pexels-photo-69494.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user8 = User.create( email: 'joyce@user.io', password: 'password', first_name: 'Joyce', last_name: 'Davis', city: 'Philadelphia', state: 'PA', image_url: "https://images.pexels.com/photos/66152/pexels-photo-66152.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user9 = User.create( email: 'justin@user.io', password: 'password', first_name: 'Justin', last_name: 'Smith', city: 'San Antonio', state: 'TX', image_url: "https://images.pexels.com/photos/108157/pexels-photo-108157.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user10 = User.create( email: 'john@user.io', password: 'password', first_name: 'John', last_name: 'Johnson', city: 'San Diego', state: 'CA', image_url: "https://images.pexels.com/photos/59554/pexels-photo-59554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user11 = User.create( email: 'jackson@user.io', password: 'password', first_name: 'Jackson', last_name: 'Williams', city: 'New York', state: 'NY', image_url: "https://images.pexels.com/photos/41008/cowboy-ronald-reagan-cowboy-hat-hat-41008.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user12 = User.create( email: 'peter@user.io', password: 'password', first_name: 'Peter', last_name: 'Smith', city: 'San Jose', state: 'CA', image_url: "https://images.pexels.com/photos/25758/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user13 = User.create( email: 'carolyn@user.io', password: 'password', first_name: 'Carolyn', last_name: 'Jones', city: 'Bronx', state: 'NY', image_url: "https://images.pexels.com/photos/58463/pexels-photo-58463.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user14 = User.create( email: 'fred@user.io', password: 'password', first_name: 'Fred', last_name: 'Taylor', city: 'Brooklyn', state: 'NY', image_url: "https://images.pexels.com/photos/105543/pexels-photo-105543.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user15 = User.create( email: 'jeremy@user.io', password: 'password', first_name: 'Jeremy', last_name: 'Lin', city: 'San Francisco', state: 'CA', image_url: "https://images.pexels.com/photos/7823/selfie.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")
user16 = User.create( email: 'michael@user.io', password: 'password', first_name: 'Michael', last_name: 'Smith', city: 'New York', state: 'NY', image_url: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1")


#businesses
levain_bakery = Business.create( yelp_id: "H4jJ7XB3CetIr1pg56CczQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/DH29qeTmPotJbCSzkjYJwg/o.jpg")
7th_street_burger = Business.create( yelp_id: "8xpGj_YkI2X6QxqXUJPw7g", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/GYqi52GZUNzGvDScteUQ8A/o.jpg")
la_contenta = Business.create( yelp_id: "6Ct7OeTRn4caY9g0swFBsw", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/FwZAyPgdKdPGQ8aAGKh3-w/o.jpg")
benemon = Business.create( yelp_id: "axqp3pGJXnTLgq2QrPyDyQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/5ZRHsFgkyoSzac8ofvhvvg/o.jpg")
da_andrea = Business.create( yelp_id: "hdiuRS9sVZSMReZm4oV5SA", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/ZbJxx7Rl8fUH7Pg4GU2p3g/o.jpg")
rosies = Business.create( yelp_id: "9aJ1MVTthZw3QjqoG7mPjg", photo: "https://s3-media1.fl.yelpcdn.com/bphoto/C5Mf9gLWxbTiTzmOp2B2YQ/o.jpg")
xing_fu_tang = Business.create( yelp_id: "bVJQEeRNi34-3XN_F1AZEg", photo: "https://s3-media1.fl.yelpcdn.com/bphoto/vRLClNBs5NT0aQRYyLzYGg/o.jpg")
joes_italian_deli = Business.create( yelp_id: "59hEst-eXa_psEtiZMLU6A", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/CcvhN7Hdsuj1XVrXVUFiFQ/o.jpg")
tonchin = Business.create( yelp_id: "OFfZUS-nu6NDnsWe1B2bUQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/Xu78RamVyuKvKqV8IDrvsw/o.jpg")
domodomo = Business.create( yelp_id: "BPZfuPvSxCfoppU4lPFm0Q", photo: "https://s3-media1.fl.yelpcdn.com/bphoto/YX89PDM_-aBCL2USyNyhuw/o.jpg")
the_uncommons = Business.create( yelp_id: "h6qbszNgXgjj9Lrb62m-9w", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/23Mnb_KXYfPD2SAzEvB6YA/o.jpg")
arabica = Business.create( yelp_id: "ED7A7vDdg8yLNKJTSVHHmg", photo: "https://s3-media4.fl.yelpcdn.com/bphoto/_3VSEFG3iUT-M66JYc7U4w/o.jpg")
sweet_moment = Business.create( yelp_id: "UZViRVpxNZvOM5KarmbT1g", photo: "https://s3-media4.fl.yelpcdn.com/bphoto/9FgfPV5mK-FbcS6m3v-Nvg/o.jpg")
her_name_is_han = Business.create( yelp_id: "qY1o1MhoRyN84RRhUJtvpQ", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/SBjw3d1VlqSVEU5KMYpDdQ/o.jpg")
lappartement_4f = Business.create( yelp_id: "zMzH5TN6uieQj_mM68aUkw", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/3OKcDMAA5VsRHeJnyrKstw/o.jpg")
hakka_cuisine = Business.create( yelp_id: "OXNPuN7KcjP9T5DdilgzdQ", photo: "https://s3-media1.fl.yelpcdn.com/bphoto/DJIlWc9RS-7OYEIs05yvBw/o.jpg")
house_of_joy = Business.create( yelp_id: "9U5tPyF6QEiVntlyTemxKA", photo: "https://s3-media4.fl.yelpcdn.com/bphoto/B3zS6dwpVYSKPQITTvpJNQ/o.jpg")
gagopa_karaoke = Business.create( yelp_id: "D2AESr-Px4rMw7yLlCmLkQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/by0H42IKgvpbpv1j0ORVXg/o.jpg")
okiboru_house_of_tsukemen = Business.create( yelp_id: "FFzCto6PhZYZGUZLOICbTg", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/ZMLX6Znie-C78KABf0LawA/o.jpg")
app_academy_nyc = Business.create( yelp_id: "fRfkzhgwDjKU72NCxNuKmg", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/zc_-5oyQ_8J1Ym9Ei0mU4g/o.jpg")
texas_pit_stop_bbq = Business.create( yelp_id: "oFlG0LmtqujRty181Cmztw", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/x2act_IsP8-PtLA4yZQ_zA/o.jpg")
abaca = Business.create( yelp_id: "u2KkG0ucvooOdwgIgZPSlA", photo: "https://s3-media1.fl.yelpcdn.com/bphoto/C9u-0TKuuNmL3qjz5uz3PQ/o.jpg")
kann = Business.create( yelp_id: "pHO-ZgRRZR7FM_GkEpAASA", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/gmt7ym9vSmsp-AAd-Ls2gg/o.jpg")
tito_and_pep = Business.create( yelp_id: "tkyHFPJ3dBsjE2hA_tk_sQ", photo: "https://s3-media4.fl.yelpcdn.com/bphoto/JZdDgPdOYdPziHRY1j1yWQ/o.jpg")
locust = Business.create( yelp_id: "IWRClXjIBarIbY7WUWV-ug", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/mY2Gb4A--GAQscRNqz25MA/o.jpg")
kittys_cafe = Business.create( yelp_id: "HZ1IvAelEY5xnjBt9f5L2A", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/5kiMZpIVfiOF4kpwgPOZeg/o.jpg")
pemberton phx = Business.create( yelp_id: "FjaGfXVysSbOBnv0T41v3Q", photo: "https://s3-media2.fl.yelpcdn.com/bphoto/vLcWNaFWKH0GhLzYtrFL6Q/o.jpg")
neptune_oyster = Business.create( yelp_id: "y2w6rFaO0XEiG5mFfOsiFA", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/ZVaN5dj-yCVIiPk7VtFhOw/o.jpg")
elvies = Business.create( yelp_id: "D-j2c3FmU639dGW-4NZIWQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/RXsWyInSnW4seHdWf91OIg/o.jpg")
brennans = Business.create( yelp_id: "ku8cAVBLaF_4rI-yK6gNnQ", photo: "https://s3-media3.fl.yelpcdn.com/bphoto/c1YZ71bFC6sJdKDxzNvbGg/o.jpg")


#reviews
review1 = Review.create( text: "Cookies galore! Some of the best cookies that I've had", food_rating: 5, service_rating: 5, author_id: 3, business_id: 1)
review2 = Review.create( text: "Mixed feelings with this burger! Ordered delivery and it was quite fast, the meal came hot so we were pretty excited! Had a double burger and the regular one. I would say... it tasted very good but it was by far the greasiest burger I have ver had in my life. Patty was really average, fast food patty. Size is pretty small for the price... so not sure either if I would ever order from here again... Fries ok. The cost was over $30 so again, dont think will repeat", food_rating: 3, service_rating: 5, author_id: 4, business_id: 2)
review3 = Review.create( text: "The carnitas were very tender, and while the menu warns the serrano salsa they are served with is very spicy I didn't think it was spicy at all, just flavorful.", food_rating: 4, service_rating: 5, author_id: 5, business_id: 3)
review4 = Review.create( text: "Cute spot in east village! Cute interior ambience and the wait staff are all very friendly.", food_rating: 5, service_rating: 5, author_id: 6, business_id: 4)
review5 = Review.create( text: "Been here a couple of times. Super friendly staff. Good food. Definitely recommend!", food_rating: 5, service_rating: 5, author_id: 7, business_id: 5)
review6 = Review.create( text: "Rosie's is a great restaurant. I was captivated by the ladies in the center making tortillas, and it tasted as good as I thought it would.", food_rating: 5, service_rating: 5, author_id: 8, business_id: 6)
review7 = Review.create( text: "The line forms around the block even before they open.... But it's worth the wait, usually!", food_rating: 5, service_rating: 4, author_id: 9, business_id: 7)
review8 = Review.create( text: "The bread to filling ratio seemed really off to me and with there being too much bread, it made the sandwich seem a little dry. I liked the honey mustard and the chicken cutlet was crispy and seasoned well.", food_rating: 4, service_rating: 5, author_id: 10, business_id: 8)
review9 = Review.create( text: "Wow! Blown away by everything here, it definitely deserves its Michelin star", food_rating: 5, service_rating: 5, author_id: 11, business_id: 9)
review10 = Review.create( text: "Having been here twice now, I will say come for the hand rolls. Not all hand rolls will be amazing (which is a bummer), but what they do right, they do amazingly.", food_rating: 4, service_rating: 5, author_id: 12, business_id: 10)
review11 = Review.create( text: "I LOVE this place and I honestly wish there were more like it. To my knowledge, it is the only board game bar in the city of its nature. Now there are other bars that do have board games but this particular spot is specifically catering to exclusively board games only (so no ping pong, darts, pool, none of that). It's a sit down and play kind of vibe. They do sell drinks but it's more just ciders and beers", food_rating: 2, service_rating: 5, author_id: 13, business_id: 11)
review12 = Review.create( text: "", food_rating: , service_rating: , author_id: 14, business_id: 12)
review13 = Review.create( text: "", food_rating: , service_rating: , author_id: 15, business_id: 13)
review14 = Review.create( text: "", food_rating: , service_rating: , author_id: 16, business_id: 14)
review15 = Review.create( text: "", food_rating: , service_rating: , author_id: 3, business_id: 15)
review16 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 16)
review17 = Review.create( text: "", food_rating: , service_rating: , author_id: 5, business_id: 17)
review18 = Review.create( text: "", food_rating: , service_rating: , author_id: 6, business_id: 18)
review19 = Review.create( text: "", food_rating: , service_rating: , author_id: 7, business_id: 19)
review20 = Review.create( text: "", food_rating: , service_rating: , author_id: 8, business_id: 20)
review21 = Review.create( text: "", food_rating: , service_rating: , author_id: 9, business_id: 21)
review22 = Review.create( text: "", food_rating: , service_rating: , author_id: 10, business_id: 22)
review23 = Review.create( text: "", food_rating: , service_rating: , author_id: 11, business_id: 23)
review24 = Review.create( text: "", food_rating: , service_rating: , author_id: 12, business_id: 24)
review25 = Review.create( text: "", food_rating: , service_rating: , author_id: 13, business_id: 25)
review26 = Review.create( text: "", food_rating: , service_rating: , author_id: 14, business_id: 26)
review27 = Review.create( text: "", food_rating: , service_rating: , author_id: 15, business_id: 27)
review28 = Review.create( text: "", food_rating: , service_rating: , author_id: 16, business_id: 28)
review29 = Review.create( text: "", food_rating: , service_rating: , author_id: 3, business_id: 29)
review30 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 30)
review31 = Review.create( text: "The Cookie Monster in me cannot be tamed whenever I pay a visit to my favorite NY cookie shop.  As I write, I'm remembering the huge warm gooey bite of one of the best cookies known to humans. I've only been twice but it's left such an indelible mark on my life that I've attempted to bake these delectable thick cookies at home.", food_rating: 5, service_rating: 5, author_id: 5, business_id: 1)
review32 = Review.create( text: "The burgers are actually really tasty. Is it worth it for the price? That's up to you, probably not as it is a small burger. They could improve their service and friendliness though.", food_rating: 5, service_rating: 2, author_id: 6, business_id: 2)
review33 = Review.create( text: "I came here specifically for the beautiful nachos I kept seeing on Yelp and they did not disappoint! The restaurant is tiny with only a few tables and some covered outdoor seating. Service was standard.", food_rating: 5, service_rating: 4, author_id: 7, business_id: 3)
review34 = Review.create( text: "Highly recommend the una tama don if you are looking for a bowl of soul warming food! It's sweet, savory, warm, tender and just melts in your mouth! The egg, unagi, and shiitake mushroom are in perfect harmony.", food_rating: 5, service_rating: 5, author_id: 8, business_id: 4)
review35 = Review.create( text: "The food is amazing and the service is great but unfortunately the price is too high to justify the flavor", food_rating: 4, service_rating: 5, author_id: 9, business_id: 5)
review36 = Review.create( text: "The tacos in my opinion were kinda cold/warmish. It's only a two maybe three bite taco so by the time I'm into my second bite it's too late to take it back. The server was amazing though very attentive despite the activity and even offered to take a picture elf my friend and I.", food_rating: 4, service_rating: 5, author_id: 10, business_id: 6)
review37 = Review.create( text: "Only downfall is some of the drinks on the menu on the TVs aren't on the menus when you go to the register to order. You can a still order them but it would be nice to have the same menus on the TV and at the register", food_rating: 5, service_rating: 4, author_id: 11, business_id: 7)
review38 = Review.create( text: "What a place. I highly recommend when in the area. It is a little off the beaten path from Arthur Ave but definitely come by. 5 stars all the way.", food_rating: 5, service_rating: 5, author_id: 12, business_id: 8)
review39 = Review.create( text: "My go to Ramen shop now, Tonchin lives up to the hype. Super hard to get a table anywhere near prime eating times but worth the wait or off-hour time slot", food_rating: 5, service_rating: 5, author_id: 13, business_id: 9)
review40 = Review.create( text: "What an incredible place! The ambience, the food, the drinks - all so amazing! Definitely make a reservation before coming.", food_rating: 5, service_rating: 5, author_id: 14, business_id: 10)
review41 = Review.create( text: "This was my first experience at a board game cafe and it was amazing. There were so many options and the atmosphere was pleasant. The place is always booked/a bit of a wait so it's something you have to plan for. I which it was more walk in friendly for a spontaneous drop in. Needs more food options to snack on!", food_rating: 1, service_rating: 5, author_id: 15, business_id: 11)
review42 = Review.create( text: "", food_rating: , service_rating: , author_id: 16, business_id: 12)
review43 = Review.create( text: "", food_rating: , service_rating: , author_id: 3, business_id: 13)
review44 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 14)
review45 = Review.create( text: "", food_rating: , service_rating: , author_id: 5, business_id: 15)
review46 = Review.create( text: "", food_rating: , service_rating: , author_id: 6, business_id: 16)
review47 = Review.create( text: "", food_rating: , service_rating: , author_id: 7, business_id: 17)
review48 = Review.create( text: "", food_rating: , service_rating: , author_id: 8, business_id: 18)
review49 = Review.create( text: "", food_rating: , service_rating: , author_id: 9, business_id: 19)
review50 = Review.create( text: "", food_rating: , service_rating: , author_id: 10, business_id: 20)
review51 = Review.create( text: "", food_rating: , service_rating: , author_id: 11, business_id: 21)
review52 = Review.create( text: "", food_rating: , service_rating: , author_id: 12, business_id: 22)
review53 = Review.create( text: "", food_rating: , service_rating: , author_id: 13, business_id: 23)
review54 = Review.create( text: "", food_rating: , service_rating: , author_id: 14, business_id: 24)
review55 = Review.create( text: "", food_rating: , service_rating: , author_id: 15, business_id: 25)
review56 = Review.create( text: "", food_rating: , service_rating: , author_id: 16, business_id: 26)
review57 = Review.create( text: "", food_rating: , service_rating: , author_id: 3, business_id: 27)
review58 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 28)
review59 = Review.create( text: "", food_rating: , service_rating: , author_id: 5, business_id: 29)
review60 = Review.create( text: "", food_rating: , service_rating: , author_id: 6, business_id: 30)
review61 = Review.create( text: "This place may be a favorite for some, but I wasn't a fan. Cookies are very heavy in chocolate, so much so that they have an almost acidic flavor. Chocolate lovers may be a fan of this ratio but I prefer a more balanced cookie. Service was okay but slightly slow", food_rating: 2, service_rating: 4, author_id: 7, business_id: 1)
review62 = Review.create( text: "7th Street is one of the best smash burgers in the city. It is a perfect pop-in place for any meal and definitely fits in the affordable category. I got a single burger topped with cheese, grilled onions, pickles, and special sauce. The single patty wouldn't have been enough but I also shared an order of the chopped beef fries. They are not on the menu but it is a must to ask. Fries topped with special sauce, grilled onions, and a burger patty. The fries were on the pricier side ($11) but the burger was $6.50, which is perfect for the serving. This was a large amount of food but fries are perfect for sharing! Highly recommended", food_rating: 5, service_rating: 5, author_id: 8, business_id: 2)
review63 = Review.create( text: "Been craving Huevos Rancheros and Clinton Street stoped making them post COVID.  Found this place on yelp, and Yelpers didn't disappoint.", food_rating: 5, service_rating: 5, author_id: 9, business_id: 3)
review64 = Review.create( text: "Had high hopes for Benemon but ultimately it was a bit of a letdown. Walked in around 6:20 on a weeknight and got a table for two immediately. The una-tama don was fantastic, but the karaage was kind of soggy - super unappealing, maybe it was laying out for a bit. Pork Katsu curry was decent, though again, the katsu itself could have been crispier.", food_rating: 3, service_rating: 5, author_id: 10, business_id: 4)
review65 = Review.create( text: "1st time at this location and not impressed. Pork Shank special was tough and Sole special was dry but we're easy so no problem until the bus guy asked if i liked the meal. I simply said it was tough. The server returns on the attack wondering why i didn't tell her? We were going to order dessert and come back another time but after the attitude why even return. I guess I'll just head up to La Masseria when I want italian. I rarely write a review but this time I had no choice.", food_rating: 2, service_rating: 1, author_id: 11, business_id: 5)
review66 = Review.create( text: "I have never had a bad meal at Rosie's, but this last time there outdid itself. Our waitress was also amazing!", food_rating: 5, service_rating: 5, author_id: 12, business_id: 6)
review67 = Review.create( text: "I ordered the brown sugar boba milk and it was delicious. The torched sugar on top added such a great flavor and overall it was a very well-balanced drink. Drinks came out super fast and it was a great treat after dinner. I'd definitely come again!", food_rating: 5, service_rating: 5, author_id: 13, business_id: 7)
review68 = Review.create( text: "Love Joe's. One of the best deli's in Belmont, Bronx near Arthur Ave. I've gotten the last meal, the goodfella sandwich, DSNY the strongest all delicious. ", food_rating: 5, service_rating: 5, author_id: 14, business_id: 8)
review69 = Review.create( text: "The food was pretty good, but I'm not crazy about it. It's a Michelin star restaurant, but I guess my expectations were too high. The noodles were flavorful and the soup was tasty and seasoned well, but it just personally did not stand out to me, is something I'm fine with not having again. Service was superb, however.", food_rating: 3, service_rating: 5, author_id: 15, business_id: 9)
review70 = Review.create( text: "The domokase course was definitely unique. I really enjoyed trying a wide variety of dishes and types of seafood. Their fish is good and fresh, not the most mindblowingly quality, but they do have unique and interesting flavor combinations that I have not seen before. Additionally, their service is was wonderful. I really enjoyed experience. I would come back and suggest it to my friends!", food_rating: 5, service_rating: 5, author_id: 16, business_id: 10)
review71 = Review.create( text: "The service was top notch everyone was super friendly and tried to help as much as they can. The coffee is not my favorite drink so next time I will prob try something else.", food_rating: 2, service_rating: 5, author_id: 3, business_id: 11)
review72 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 12)
review73 = Review.create( text: "", food_rating: , service_rating: , author_id: 5, business_id: 13)
review74 = Review.create( text: "", food_rating: , service_rating: , author_id: 6, business_id: 14)
review75 = Review.create( text: "", food_rating: , service_rating: , author_id: 7, business_id: 15)
review76 = Review.create( text: "", food_rating: , service_rating: , author_id: 8, business_id: 16)
review77 = Review.create( text: "", food_rating: , service_rating: , author_id: 9, business_id: 17)
review78 = Review.create( text: "", food_rating: , service_rating: , author_id: 10, business_id: 18)
review79 = Review.create( text: "", food_rating: , service_rating: , author_id: 11, business_id: 19)
review80 = Review.create( text: "", food_rating: , service_rating: , author_id: 12, business_id: 20)
review81 = Review.create( text: "", food_rating: , service_rating: , author_id: 13, business_id: 21)
review82 = Review.create( text: "", food_rating: , service_rating: , author_id: 14, business_id: 22)
review83 = Review.create( text: "", food_rating: , service_rating: , author_id: 15, business_id: 23)
review84 = Review.create( text: "", food_rating: , service_rating: , author_id: 16, business_id: 24)
review85 = Review.create( text: "", food_rating: , service_rating: , author_id: 3, business_id: 25)
review86 = Review.create( text: "", food_rating: , service_rating: , author_id: 4, business_id: 26)
review87 = Review.create( text: "", food_rating: , service_rating: , author_id: 5, business_id: 27)
review88 = Review.create( text: "", food_rating: , service_rating: , author_id: 6, business_id: 28)
review89 = Review.create( text: "", food_rating: , service_rating: , author_id: 7, business_id: 29)
review90 = Review.create( text: "", food_rating: , service_rating: , author_id: 8, business_id: 30)